language: shell
matrix:
  include:
    - name: "Windows VS2017"
      os: windows
      script:
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && msbuild.exe Cpp/Windows/TestCpu.sln /p:Configuration=Release'

    - name: "Mac Xcode 10.1/clang"
      os: osx
      osx_image: xcode10.1
      script:
        - xcodebuild -project Cpp/Apple/Test.xcodeproj -configuration Release -scheme 'Test Mac' build

    - name: "iOS Xcode 10.1/clang"
      os: osx
      osx_image: xcode10.1
      script:
        - xcodebuild -project Cpp/Apple/Test.xcodeproj -configuration Release -scheme 'Test iOS' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
